import type { Config } from 'tailwindcss';

/**
 * GadiSewa Design System — "Sky Blue" palette (primary #0ea5e9) + slate neutrals,
 * matched to the latest Figma sign-up design. Semantic Material-style tokens.
 * `primary-container`/`on-primary-container` = vivid sky-blue + white so solid
 * `bg-primary-container` buttons match the design's filled buttons.
 */
const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        'surface': '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f8fafc',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e8f0',
        'on-surface': '#1e293b',
        'on-surface-variant': '#475569',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f1f1f1',
        'outline': '#94a3b8',
        'outline-variant': '#cbd5e1',
        'surface-tint': '#0ea5e9',
        'primary': '#0ea5e9',
        'on-primary': '#ffffff',
        'primary-container': '#0ea5e9',
        'on-primary-container': '#ffffff',
        'inverse-primary': '#7dd3fc',
        'secondary': '#64748b',
        'on-secondary': '#ffffff',
        'secondary-container': '#f1f5f9',
        'on-secondary-container': '#334155',
        'tertiary': '#006e2f',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#00b050',
        'on-tertiary-container': '#003a15',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#bae6fd',
        'primary-fixed-dim': '#7dd3fc',
        'on-primary-fixed': '#082f49',
        'on-primary-fixed-variant': '#0369a1',
        'secondary-fixed': '#e2e8f0',
        'secondary-fixed-dim': '#cbd5e1',
        'on-secondary-fixed': '#0f172a',
        'on-secondary-fixed-variant': '#474646',
        'tertiary-fixed': '#6bff8f',
        'tertiary-fixed-dim': '#4ae176',
        'on-tertiary-fixed': '#002109',
        'on-tertiary-fixed-variant': '#005321',
        'background': '#ffffff',
        'on-background': '#1e293b',
        'surface-variant': '#f1f5f9',
      },
      fontFamily: {
        'headline-xl': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '16px', fontWeight: '600' }],
      },
      spacing: {
        'unit': '4px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
        'gutter': '16px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'container-max': '1280px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};

export default config;
